### ISSUE TITLE
Error using python APP in Xubuntu 16.04

### ISSUE THREAD

**Issue by dcialdella** [toolsprods/SniffVPN#1]
```
          .---..-. .-,-,---,---.-.   .-,---. .-. .-.
         ( .-._|  \| |(| .-| .-'\ \ / /| .-.\|  \| |
        (_) \  |   | (_| `-| `-. \ V / | |-' |   | |
        _  \ \ | |\  | | .-| .-'  ) /  | |--'| |\  |
       ( `-'  )| | |)| | | | |   (_)   | |   | | |)|
        `----' /(  (_`-)\| )\|         /(    /(  (_)
              (__)    (__)(__)        (__)  (__)
```

[---]         SniffVPN - Traffic monitor for your VPN          [---]
[---]          Created by: Alvaro Nunez (toolsprods)           [---]
[---]                     Version: 0.1                         [---]
[---]                Codename: 'Alfa Version'                  [---]
[---]        Follow me on GitHub: github.com/toolsprods/       [---]

[_] Running server at 10.8.0.1:8000...
[_] Can see statics and logs at 10.8.0.1:8000/panel

Traceback (most recent call last):
  File "SniffVPN.py", line 113, in <module>
    main()
  File "SniffVPN.py", line 109, in main
    sniff(iface=interface, prn=packet, count=count)
  File "/usr/lib/python2.7/dist-packages/scapy/sendrecv.py", line 586, in sniff
    r = prn(p)
  File "SniffVPN.py", line 79, in packet
    iporig=getOriginalIP(ipsrc)
  File "SniffVPN.py", line 94, in getOriginalIP
    return ipOrig[2].split(':')[0]
UnboundLocalError: local variable 'ipOrig' referenced before assignment

**Comment by toolsprods** [comment]
Hi dcialdella,

thanks for the report. How you have made the installation of the VPN? You use OpenVPN? What operating system are you working?

It seems that not find the original ip in the **OpenVPN log file**. I will check it.

Thanks.

**Comment by dcialdella** [comment]
Xubuntu 16.04
I installed and use OpenVpn daily.
it works perfectly.

thanks

**Comment by toolsprods** [comment]
Okay. Sorry to say that this first version has been generated on Raspbian (it´s a project still in alpha phase), so the files might have different routes and even the OpenVPN log file can be something different.

I'm working on adapting it to other operating systems. I try to do a test with Xubuntu as soon as possible.

**Comment by dcialdella** [comment]
I could help you if you want. This is what iḿ doing now.... do think these posts as complains.... it's the way to improve it.

**Comment by toolsprods** [comment]
Of course! It's good for the project. As you say in the issue #3, look at the code and suggest me anything. If you want more information about the code, contact me via email.

Regards!

**Comment by toolsprods** [comment]
Renamed to specify "Error APP in python using Xubuntu 16.04".

It is pending to be updated to support other operating systems.
